language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28

before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew

script: "./gradlew build --stacktrace"
